version: 2
sources:
 - name: CRM_MEG_PRD
   database: CRM_MEG_PRD_DB
   schema: crm_meg_prd
   tables:
     - name: contact
     - name: elogic_medicalcondition
     - name: elogic_usedproduct
     - name: product
     - name: stringmap
     - name: elogic_manufacturers
     - name: SYSTEMUSER
     - name: ACCOUNT
     - name: ELOGIC_PRODUCTTYPE
     - name: BUSINESSUNIT
